services:
  # Web service for the main application (includes cron jobs for free tier)
  - type: web
    name: youtube-automation-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: Europe/London
      - key: PORT
        value: 10000
      - key: CRON_SCHEDULE_TYPE
        value: sixPerDay
    healthCheckPath: /health
    autoDeploy: true
